--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Junho-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VDIC_CONSUMO_N95
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DBAMV"."VDIC_CONSUMO_N95" ("CD_SETOR", "NM_SETOR", "CD_PRODUTO", "DT_MVTO_ESTOQUE", "COTA", "CONSUMO", "DIFERENCA") AS 
  SELECT   r.cd_setor, 
         s.nm_setor, 
         p.cd_produto, 
         r.dt_mvto_estoque, 
         SUM (NVL(cota, 0)) AS cota,
         SUM (NVL (consumo, 0)) AS consumo,   
         SUM (NVL (consumo, 0)) - SUM (NVL (cota, 0)) AS diferenca
FROM (SELECT c.cd_setor, 
             c.cd_produto, ROUND ((c.qt_cota / c.nr_dias) * 30) AS cota,
             0 AS consumo, NULL AS dt_mvto_estoque
      FROM dbamv.cota_setor c
      WHERE TO_CHAR (c.cd_produto) LIKE '154590'
          UNION
      SELECT   m.cd_setor, i.cd_produto, 0 AS cota,
               SUM (i.qt_movimentacao * u.vl_fator) AS consumo, m.dt_mvto_estoque
      FROM dbamv.mvto_estoque m, dbamv.itmvto_estoque i, dbamv.uni_pro u
      WHERE TO_CHAR (m.dt_mvto_estoque, 'yyyy') LIKE '2020'
            AND m.tp_mvto_estoque IN ('P', 'S')
            AND TO_CHAR (i.cd_produto) LIKE '154590'
            AND m.cd_mvto_estoque = i.cd_mvto_estoque
            AND i.cd_uni_pro = u.cd_uni_pro
       GROUP BY m.dt_mvto_estoque, m.cd_setor, i.cd_produto) r,
       dbamv.setor s,
       dbamv.especie e,
       dbamv.produto p
WHERE e.tp_especie IN ('A', 'E')
     AND r.cd_setor = s.cd_setor
     AND p.cd_produto = r.cd_produto
     AND p.cd_especie = e.cd_especie
GROUP BY r.cd_setor, s.nm_setor, p.cd_produto, r.dt_mvto_estoque
  HAVING SUM (NVL (consumo, 0)) > SUM (NVL (cota, 0))
ORDER BY 3, r.dt_mvto_estoque;
REM INSERTING into DBAMV.VDIC_CONSUMO_N95
SET DEFINE OFF;
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('09/01/20','DD/MM/RR'),'0','50','50');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('17/01/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('44','ARMATE - ÁREA  MAT. ESTERILIZA','154590',to_date('23/01/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('44','ARMATE - ÁREA  MAT. ESTERILIZA','154590',to_date('30/01/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('05/02/20','DD/MM/RR'),'0','100','100');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('21/02/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('21/02/20','DD/MM/RR'),'0','50','50');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('28/02/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('28/02/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('44','ARMATE - ÁREA  MAT. ESTERILIZA','154590',to_date('06/03/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('09/03/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('244','ARINT - ÁREA ADMISSÃO E INTERN','154590',to_date('17/03/20','DD/MM/RR'),'0','23','23');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('18/03/20','DD/MM/RR'),'0','30','30');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('19/03/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('20/03/20','DD/MM/RR'),'0','17','17');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('26/03/20','DD/MM/RR'),'0','37','37');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('481','ARTRAR - ÁREA TRAUMA REFERENCI','154590',to_date('26/03/20','DD/MM/RR'),'0','35','35');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('44','ARMATE - ÁREA  MAT. ESTERILIZA','154590',to_date('27/03/20','DD/MM/RR'),'0','25','25');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('31/03/20','DD/MM/RR'),'0','1','1');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('31/03/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('31/03/20','DD/MM/RR'),'0','32','32');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('31/03/20','DD/MM/RR'),'0','2','2');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('01/04/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('02/04/20','DD/MM/RR'),'0','37','37');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('03/04/20','DD/MM/RR'),'0','7','7');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('03/04/20','DD/MM/RR'),'0','35','35');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('07/04/20','DD/MM/RR'),'0','78','78');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('07/04/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('07/04/20','DD/MM/RR'),'0','3','3');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('08/04/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('08/04/20','DD/MM/RR'),'0','118','118');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('08/04/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('08/04/20','DD/MM/RR'),'0','2','2');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('09/04/20','DD/MM/RR'),'0','30','30');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('09/04/20','DD/MM/RR'),'0','4','4');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('09/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('599','ATEINP - ÁREA TERAP. INT. PED','154590',to_date('09/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('13/04/20','DD/MM/RR'),'0','2','2');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('14/04/20','DD/MM/RR'),'0','102','102');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('14/04/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('15/04/20','DD/MM/RR'),'0','8','8');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('16/04/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('16/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('16/04/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('17/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('20/04/20','DD/MM/RR'),'0','44','44');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('19','COASS - COORD. ASSISTENCIAL','154590',to_date('22/04/20','DD/MM/RR'),'0','1','1');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('22/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('481','ARTRAR - ÁREA TRAUMA REFERENCI','154590',to_date('22/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('24/04/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('24/04/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('24/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('599','ATEINP - ÁREA TERAP. INT. PED','154590',to_date('24/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('27/04/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('28/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('29/04/20','DD/MM/RR'),'0','31','31');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('25','ARMIN - ÁREA MEDICINA INTERNA','154590',to_date('29/04/20','DD/MM/RR'),'0','1','1');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('29/04/20','DD/MM/RR'),'0','40','40');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('29/04/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('5','DIENP -  DIV. ENSINO PESQUISA','154590',to_date('30/04/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('32','AREAB - ÁREA DE REABILITAÇÃO','154590',to_date('30/04/20','DD/MM/RR'),'0','3','3');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('30/04/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('30/04/20','DD/MM/RR'),'0','4','4');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('04/05/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('04/05/20','DD/MM/RR'),'0','150','150');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('04/05/20','DD/MM/RR'),'0','14','14');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('05/05/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('05/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('599','ATEINP - ÁREA TERAP. INT. PED','154590',to_date('05/05/20','DD/MM/RR'),'0','16','16');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('06/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('155','ARPED - ÁREA DE PEDIATRIA','154590',to_date('06/05/20','DD/MM/RR'),'0','3','3');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('481','ARTRAR - ÁREA TRAUMA REFERENCI','154590',to_date('06/05/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('07/05/20','DD/MM/RR'),'0','25','25');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('483','UIN7 - UNID. INT. 7 ANDAR','154590',to_date('07/05/20','DD/MM/RR'),'0','150','150');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('08/05/20','DD/MM/RR'),'0','25','25');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('11/05/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('11/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('155','ARPED - ÁREA DE PEDIATRIA','154590',to_date('11/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('12/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('12/05/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('13/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('14/05/20','DD/MM/RR'),'0','2','2');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('14/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('15/05/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('18/05/20','DD/MM/RR'),'0','57','57');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('18/05/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('18/05/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('20/05/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('21/05/20','DD/MM/RR'),'0','100','100');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('21/05/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('25','ARMIN - ÁREA MEDICINA INTERNA','154590',to_date('22/05/20','DD/MM/RR'),'0','43','43');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('22/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('22/05/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('32','AREAB - ÁREA DE REABILITAÇÃO','154590',to_date('25/05/20','DD/MM/RR'),'0','25','25');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('25/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('26/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('246','AREAMB- ÁREA AMBULATORIAL','154590',to_date('26/05/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('27/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('244','ARINT - ÁREA ADMISSÃO E INTERN','154590',to_date('27/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('27/05/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('481','ARTRAR - ÁREA TRAUMA REFERENCI','154590',to_date('27/05/20','DD/MM/RR'),'0','5','5');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('28/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('29/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('29/05/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('01/06/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('01/06/20','DD/MM/RR'),'0','150','150');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('220','ARMEN - ÁREA DE SAÚDE MENTAL','154590',to_date('01/06/20','DD/MM/RR'),'0','20','20');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('02/06/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('03/06/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('03/06/20','DD/MM/RR'),'0','100','100');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('04/06/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('485','ARGH -ÁREA GER. HOTELARIA HOSP','154590',to_date('05/06/20','DD/MM/RR'),'0','16','16');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('08/06/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('481','ARTRAR - ÁREA TRAUMA REFERENCI','154590',to_date('08/06/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('36','ACCIR - ÁREA CENTRO CIRÚRGICO','154590',to_date('09/06/20','DD/MM/RR'),'0','15','15');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('22','ARCIR-AREA ALMOX. C. CIRURGIC','154590',to_date('12/06/20','DD/MM/RR'),'0','10','10');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('256','AHEMO - ÁREA DE HEMOTERAPIA','154590',to_date('15/06/20','DD/MM/RR'),'0','6','6');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('26','ATEIN - ÁREA TER. INTEN. ADULT','154590',to_date('17/06/20','DD/MM/RR'),'0','90','90');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('24','ARIM - ÁREA DE IMAGEM','154590',to_date('19/06/20','DD/MM/RR'),'0','16','16');
Insert into DBAMV.VDIC_CONSUMO_N95 (CD_SETOR,NM_SETOR,CD_PRODUTO,DT_MVTO_ESTOQUE,COTA,CONSUMO,DIFERENCA) values ('35','DIENF -  DIV. DE ENFERMAGEM','154590',to_date('19/06/20','DD/MM/RR'),'0','15','15');
