select 
  ITMVTO_ESTOQUE.CD_PRODUTO, 
  PRODUTO.DS_PRODUTO, 
  SETOR.NM_SETOR, 
  SETOR.CD_SETOR, 
  ITMVTO_ESTOQUE.QT_MOVIMENTACAO, 
  UNI_PRO.VL_FATOR, 
  MVTO_ESTOQUE.DT_MVTO_ESTOQUE 
from 
  ITMVTO_ESTOQUE 
  join UNI_PRO on (
    ITMVTO_ESTOQUE.CD_PRODUTO = UNI_PRO.CD_PRODUTO
  ) 
  join MVTO_ESTOQUE on (
    ITMVTO_ESTOQUE.CD_MVTO_ESTOQUE = MVTO_ESTOQUE.CD_MVTO_ESTOQUE
  ) 
  join PRODUTO on (
    ITMVTO_ESTOQUE.CD_PRODUTO = PRODUTO.CD_PRODUTO
  ) 
  join COTA_SETOR on (
    PRODUTO.CD_PRODUTO = COTA_SETOR.CD_PRODUTO
  ) 
  join SETOR on (
    COTA_SETOR.CD_SETOR = SETOR.CD_SETOR
  ) 
where 
  ITMVTO_ESTOQUE.CD_PRODUTO in (
    SELECT 
      CD_PRODUTO 
    FROM 
      DBAMV.PRODUTO 
    WHERE 
      REGEXP_LIKE(
        DS_PRODUTO, '(AVENTAL(.*)((PROCEDIMENTO)+|(IMPERMEAVEL)+|(AZUL)+)(.*))|(MASCARA(.*)((CIRÚRGICA)+|(TRIPLA)+)(.*))|(SAPATILHA(.*)(CIRÚRGICA)+(.*))|TURBANTE(.*)(LONGO)+(.*)|(LUVA(.*)(PROCEDIMENTO)+(.*))|OCULOS(.*)(PROTEÇÃO)+(.*)'
      )
  ) 
  AND MVTO_ESTOQUE.DT_MVTO_ESTOQUE > to_date('2020-01-01', 'yyyy-mm-dd');
