SELECT
  PRODUTO.CD_PRODUTO,
  UPPER(PRODUTO.DS_PRODUTO) DS_PRODUTO,
  SUM (EST_PRO.QT_ESTOQUE_ATUAL) / DBAMV.VERIF_VL_FATOR_PROD(PRODUTO.CD_PRODUTO) QT_ESTOQUE,
  DBAMV.VERIF_DS_UNID_PROD(PRODUTO.CD_PRODUTO) DS_UNIDADE
FROM
  DBAMV.ESTOQUE ESTOQUE,
  DBAMV.EST_PRO,
  DBAMV.PRODUTO,
  DBAMV.SUB_CLAS,
  DBAMV.CLASSE,
  DBAMV.ESPECIE
WHERE
  ESTOQUE.CD_ESTOQUE = EST_PRO.CD_ESTOQUE
  AND EST_PRO.CD_PRODUTO IN (SELECT CD_PRODUTO FROM DBAMV.PRODUTO A WHERE A.CD_PRODUTO = PRODUTO.CD_PRODUTO)
  AND PRODUTO.CD_PRODUTO IN (33020103, 191400, 154590, 202592, 201375, 202606, 20800, 154614, 154590)
  AND PRODUTO.CD_SUB_CLA = SUB_CLAS.CD_SUB_CLA
  AND PRODUTO.CD_CLASSE = SUB_CLAS.CD_CLASSE
  AND PRODUTO.CD_ESPECIE = ESPECIE.CD_ESPECIE
  AND SUB_CLAS.CD_CLASSE = CLASSE.CD_CLASSE
  AND SUB_CLAS.CD_ESPECIE = ESPECIE.CD_ESPECIE
  AND CLASSE.CD_ESPECIE = ESPECIE.CD_ESPECIE
  AND PRODUTO.SN_MESTRE = 'N'
  AND PRODUTO.SN_KIT = 'N'
  AND ESTOQUE.CD_MULTI_EMPRESA = 1
GROUP BY
  PRODUTO.DS_PRODUTO,
  PRODUTO.CD_PRODUTO

